#docker-compose up
version: '3'

services:
  nodejsgdtserver:
    build:
      context: .
    ports:
      - "3010:3010"
    depends_on:
      - gdt-server

  gdt-server:
    build:
      context: ../.
    ports:
      - "3000:8080"
    volumes:
      - C:\Users\lucam\openLCA-data-1.4:/app/data
    command: -db elcd_3_2_greendelta_v2_pet_bonus_case_study
    



